[tool.ruff]
line-length = 80
target-version = "py310"
extend-exclude = [
  ".venv",
  "dist",
  "build",
  "artifacts",
  "WikidPad/**",
  "WikidPad/lib/js/**",
  "WikidPad/icons/**",
  "WikidPad/WikidPadHelp/**",
  # Exclude legacy packaging scripts from lint
  "buildWinPortZip.py",
  "setup.py",
]

[tool.ruff.lint]
select = ["E", "F", "W", "I"]

[tool.ruff.lint.isort]
known-first-party = ["WikidPad"]

[tool.black]
line-length = 80
target-version = ["py310"]
include = '\\.pyi?$'
exclude = '''
/(
    \.venv
  | dist
  | build
  | artifacts
  | WikidPad
  | buildWinPortZip\.py
  | setup(_macosx)?\.py
)/
'''
