name: gui
on: [push, pull_request]
jobs:
  linux-matrix-via-docker:
    runs-on: ubuntu-latest
    env:
      USE_SYSTEM_WX: '1'
    steps:
      - uses: actions/checkout@v4
      - name: Run matrix from scripts/distros.list (single source of truth)
        run: bash scripts/docker_matrix.sh
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: artifacts-matrix
          path: artifacts-matrix
