name: gui
on: [push, pull_request]
jobs:
  wx:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: make ci
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-artifacts
          path: artifacts
