name: gui
on: [push, pull_request]
jobs:
  wx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: bash scripts/ci_install.sh
      - run: bash scripts/ci_test_gui.sh
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-artifacts
          path: artifacts
