name: release
on:
  push:
    tags: ["v*"]

jobs:
  linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: pip
      - run: bash scripts/bootstrap.sh
      - run: bash scripts/build-pyinstaller.sh
      - uses: actions/upload-artifact@v4
        with:
          name: wikidpad-linux
          path: dist/**

  windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: python -m venv .venv
      - run: .\.venv\Scripts\pip install -U pip wheel
      - run: .\.venv\Scripts\pip install wxPython==4.2.1 -e . pyinstaller
      - run: .\.venv\Scripts\pyinstaller --name wikidpad --windowed WikidPad.py
      - uses: actions/upload-artifact@v4
        with:
          name: wikidpad-windows
          path: dist/**

